Bugfix/error handler
jooncco/spring-api-server-template pull request #3
Opened 2023-05-15 13:02 UTC by minukkim101

- 500 error handler 오류 수정
    - 404 error handler 추가

2023-05-16 06:00 UTC, jooncco requested changes

2023-05-16 06:00 UTC, jooncco commented on src/main/java/com/templates/springapiserver/config/FilterConfig.java
> +    필터를 등록할 수 있다. 다수 등록이 가능하며, 상세 필터링 내용은 등록한 필터에서 확인 가능하다.
주석이 javadoc 형식과 약간 다른것 같습니다 아미고님ㅎㅎ
번거로우시겠지만 아래처럼 나머지 주석들도 수정을 부탁드려도 될까요?
```java
/**
 * 필터를 등록할 수 있다. 다수 등록이 가능하며, 상세 필터링 내용은 등록한 필터에서 확인 가능하다.
 */
```

2023-05-16 06:00 UTC, jooncco commented on src/main/java/com/templates/springapiserver/exception/handler/GlobalExceptionHandler.java
> +        NoHandlerFoundException.class
Exception handler 가 찾아지지 않았을때, client 측 에러를 의미하는 4xx를 내려주는게 다소 어색한것 같아요ㅎㅎ
NoHandlerFoundException.class 의 경우 정말 서버에서 처리해놓지 않은 Exception을 의미하므로 500에러를 내려주면 어떨까요? 

+) BaseException 외에 Exception 들을 좀더 상세히 설계해서, 케이스별로 적절한 http status 와 response body 가 내려가도록 하는것도 좋을것 같아요!

2023-05-16 06:00 UTC, jooncco commented on src/main/java/com/templates/springapiserver/sample/controller/SampleController.java
> +    public ClientInfoDTO apiClientInfo(ClientInfoDTO clientInfoDTO) {
`질문` ResponseEntity 로 감싸지 않은 이유가 있으신가요?ㅎㅎ

2023-05-16 06:00 UTC, jooncco commented on src/main/resources/application.yml
> +<<<<<<< HEAD
merge conflict 해소가 덜 된것 같습니다ㅎㅎ

2023-05-16 06:00 UTC, jooncco commented on src/test/java/com/templates/springapiserver/SampleControllerTests.java
> +    @DisplayName("/api/client-info, API 정상 호출")
kebab-case 로 변경하신 이유가 있을까요?

2023-05-17 12:27 UTC, minukkim101 commented on src/main/java/com/templates/springapiserver/config/FilterConfig.java
> +    필터를 등록할 수 있다. 다수 등록이 가능하며, 상세 필터링 내용은 등록한 필터에서 확인 가능하다.
주석 정리는 별도 MR 로 처리할게요

2023-05-17 12:30 UTC, minukkim101 commented on src/main/java/com/templates/springapiserver/sample/controller/SampleController.java
> +    public ClientInfoDTO apiClientInfo(ClientInfoDTO clientInfoDTO) {
ㅎㅎㅎ

2023-05-17 12:31 UTC, minukkim101 commented on src/main/resources/application.yml
> +<<<<<<< HEAD
ㅎㅎㅎ add 가 안됐었네요

2023-05-17 12:31 UTC, minukkim101 commented on src/test/java/com/templates/springapiserver/SampleControllerTests.java
> +    @DisplayName("/api/client-info, API 정상 호출")
우리 어떻게 할까요?

2023-05-17 12:33 UTC, minukkim101 commented on src/main/java/com/templates/springapiserver/exception/handler/GlobalExceptionHandler.java
> +        NoHandlerFoundException.class
고민이였어요. 404는 사용자가 정의되지 않은 URL을 호출한것이니 500에러라기 보다 BAD_REQUEST로 봤는데
차라리 분리하는게 낫겠어요.

2023-05-18 06:16 UTC, jooncco commented on src/test/java/com/templates/springapiserver/SampleControllerTests.java
> +    @DisplayName("/api/client-info, API 정상 호출")
https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris
stackoverflow 티켓중에 url 컨벤션에 대한 재밌는 아규가 있네요 ㅎㅎㅎ 저도 아미고님이 하신대로 kebab-case 에 한표입니다!
@SHINMH Any thoughts?

2023-05-18 07:50 UTC, jooncco commented on src/main/java/com/templates/springapiserver/exception/handler/GlobalExceptionHandler.java
> +        NoHandlerFoundException.class
아 ... 이거 Exception 의 handler 가 찾아지지 않았을때가 아니라 404 Not Found 를 응답해야하는 상황이었군요 ㅎㅎ
지금 바꾸신 방향대로 하는게 맞는것 같습니다 :) 감사합니다

2023-05-18 07:55 UTC, merged

2023-05-19 01:32 UTC, SHINMH commented on src/test/java/com/templates/springapiserver/SampleControllerTests.java
> +    @DisplayName("/api/client-info, API 정상 호출")
저도 Kebab에 한표입니다!!